// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKv2Ilwp94IAirCg5WIrawUW2o3zyMGg',
    appId: '1:568047181976:android:4ebfcc39f959438349f0ed',
    messagingSenderId: '568047181976',
    projectId: 'first-time-setup',
    databaseURL: 'https://first-time-setup-default-rtdb.firebaseio.com',
    storageBucket: 'first-time-setup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXohVdJFfgsrnvEqGZmXmJlJrliV1zFDg',
    appId: '1:568047181976:ios:66fbaeaf5728a03249f0ed',
    messagingSenderId: '568047181976',
    projectId: 'first-time-setup',
    databaseURL: 'https://first-time-setup-default-rtdb.firebaseio.com',
    storageBucket: 'first-time-setup.appspot.com',
    androidClientId: '568047181976-jthq0aeeo1kcp996u5e25a8kh3f0n071.apps.googleusercontent.com',
    iosClientId: '568047181976-2vvdr9snn66s4am0t0l37icq7n8ihdcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorHunt',
  );
}
